version: "3.8"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm
    volumes:
      - ./:/workspace:cached
    network_mode: service:database
    command: sleep infinity
  database:
    image: "postgres"
    container_name: "cyf-postgres"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-cyf}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-opensesame}"
    ports:
      - "5432:5432"
